# Generated by Django 3.2.6 on 2022-05-16 04:59

from django.db import migrations, models
import django.db.models.deletion
import users_login.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50, verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'Departamento',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_contact', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=45, null=True, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Apellidos')),
                ('email', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Correo Electrónico')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Télefono')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='Contraseña')),
                ('workstation', models.CharField(blank=True, max_length=128, null=True, verbose_name='puesto de trabajo')),
                ('attendance', models.DateTimeField(auto_now=True, verbose_name='Horario de entrada')),
                ('is_admin', models.IntegerField(blank=True, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('is_staff', models.IntegerField(blank=True, null=True)),
                ('is_superuser', models.IntegerField(blank=True, null=True)),
                ('signup_confirmation', models.IntegerField(blank=True, null=True)),
                ('id_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users_login.department', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuario',
            },
            managers=[
                ('objects', users_login.models.UserManager()),
            ],
        ),
    ]
